server:
  port: 8082

spring:
  application:
    name: hotel-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hotel_booking?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: kk112233

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
